package main

import "time"

// log模拟
func loggerpx() {
	logger.Println("当前版本:f16d72f")
	time.Sleep(1 * time.Second)
	logger.Println("将使用 device.json 内的设备信息运行Bot.")
	logger.Println("检查签名服务器：-  (2/2)")
	time.Sleep(1 * time.Second)
	logger.Println("检查签名服务器：http://127.0.0.1:10102  (1/2)")
	logger.Println("使用签名服务器 url=http://127.0.0.1:10102, key=1145141919810, auth=-")
	logger.Println("使用签名服务器：http://127.0.0.1:10102")
	logger.Println("每 40 分钟将刷新一次签名 token")
	logger.Println("自动注册实例已关闭，请配置 sign-server 端自动注册实例以保持正常签名")
	time.Sleep(1 * time.Second)
	logger.Println("Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消.")
	time.Sleep(5 * time.Second)
	logger.Println("开始尝试登录并同步消息...")
	time.Sleep(500 * time.Millisecond)
	logger.Println("使用协议: Android Pad 8.9.63.11390")
	logger.Println("从文件 data/versions/6.json 读取协议版本 Android Pad 8.9.85.12820.")
	logger.Println("Protocol -> connect to server: 120.232.130.13:8080")
	time.Sleep(500 * time.Millisecond)
	logger.Println("token 已更新： -> 7853632b7a666c3739705966")
	logger.Println("Protocol -> device lock is disabled. HTTP API may fail.")
	time.Sleep(500 * time.Millisecond)
	logger.Println("正在检查协议更新...")
	logger.Println("检查协议更新失败: Get \"https://ghproxy.com/https://raw.githubusercontent.com/RomiChan/protocol-versions/master/android_pad.json\": read tcp 192.168.1.4:50674->155.248.215.62:443: wsarecv: An existing connection was forcibly closed by the remote host.")
	logger.Println("登录成功 欢迎使用: 帕拉斯")
	time.Sleep(500 * time.Millisecond)
	logger.Println("开始加载好友列表...")
	time.Sleep(1000 * time.Millisecond)
	logger.Println("共加载 18 个好友.")
	logger.Println("开始加载群列表...")
	logger.Println("共加载 10 个群.")
	time.Sleep(500 * time.Millisecond)
	logger.Println("资源初始化完成, 开始处理信息.")
	logger.Println("アトリは、高性能ですから!")
	logger.Println("正在检查更新.")
	time.Sleep(500 * time.Millisecond)
	logger.Println("CQ WebSocket 服务器已启动: [::]:8002")
	time.Sleep(500 * time.Millisecond)
	logger.Println("CQ HTTP 服务器已启动: [::]:9095")
	logger.Println("检查更新失败！")
	logger.Println("检查更新完成. 当前已运行最新版本.")
	logger.Println("开始诊断网络情况")
	logger.Println("网络诊断完成. 未发现问题")
}
