local: # 本地服务端的配置
  # 发送图片的延迟秒数
  image_send_delay: 2
  # websocket配置
  ws:
    # websocket监听地址
    address: 127.0.0.1
    # websocket监听端口
    port: 6700
  # http配置
  http:
    # http监听地址
    address: 127.0.0.1
    # http监听端口
    port: 5700

#远程服务器配置
remote:
  # 与配置的access-token相同，不知道这是什么可以不写
  access-token:
  ws:
    #远程websocket服务器访问链接，本地ws服务器收到的消息将会转发给此远程服务器
    url: ws://127.0.0.1:8080
  http:
    # 远程http服务器访问链接，本地http服务器收到的消息将会转发给此远程服务器
    url: http://127.0.0.1:8090
